// SQL — easy bank. Phase 1 seed (5 questions). Expand to 20 in a follow-up
// commit. Each question follows the schema in the Interview Prep V1 spec
// (rubric, expected_keywords, traps, follow_ups, time_benchmark, etc).

import type { InterviewQuestion } from "../types";

export const SQL_EASY: InterviewQuestion[] = [
  {
    id: "sql_easy_001",
    category: "SQL",
    subcategory: "Basic SELECT",
    difficulty: "easy",
    prompt: "From an `orders` table, return the top 5 customers by total spend. Show customer_id and total_spend, ordered by spend descending.",
    contextSetup:
      "Table: orders(order_id INT, customer_id INT, amount DECIMAL, order_date DATE)\n" +
      "Sample: 1,42,150.00,2024-01-15 / 2,42,75.00,2024-01-20 / 3,17,200.00,2024-01-22",
    starterCode: "-- Top 5 customers by total spend\nSELECT \n",
    sampleData: "10 rows of orders across 5 customers",
    rubric: {
      correctApproach: "GROUP BY customer_id, SUM(amount), ORDER BY DESC, LIMIT 5",
      commonMistakes: ["forgetting GROUP BY", "ordering by customer_id", "using HAVING instead of WHERE"],
      bonusPoints: ["mentions index on customer_id", "discusses NULL amount handling"],
      traps: ["NULL amounts could break SUM if not handled", "ties at rank 5 — does spec want all ties or just 5?"],
    },
    expectedKeywords: ["SELECT", "SUM", "GROUP BY", "ORDER BY", "DESC", "LIMIT"],
    followUps: ["What if amounts could be NULL?", "How would you index this for performance?"],
    relatedConcepts: ["aggregation", "sorting"],
    companiesUse: ["amazon", "snowflake", "stripe"],
    timeBenchmarkSeconds: 90,
  },
  {
    id: "sql_easy_002",
    category: "SQL",
    subcategory: "JOIN",
    difficulty: "easy",
    prompt: "Given `users` and `orders`, return every user with their order count. Include users with zero orders.",
    contextSetup:
      "users(user_id, name, email)\norders(order_id, user_id, amount)",
    starterCode: "-- Users + their order count, including zero-order users\nSELECT \n",
    sampleData: "8 users, 15 orders across 6 of them",
    rubric: {
      correctApproach: "LEFT JOIN users to orders, GROUP BY user_id, COUNT(orders.order_id)",
      commonMistakes: ["INNER JOIN drops zero-order users", "COUNT(*) instead of COUNT(orders.order_id) miscounts left-joined NULLs"],
      bonusPoints: ["uses COUNT(orders.order_id) explicitly", "uses COALESCE for clarity"],
      traps: ["zero-order users — easy to lose with INNER JOIN", "COUNT(*) on a left join counts NULLs as 1"],
    },
    expectedKeywords: ["LEFT JOIN", "COUNT", "GROUP BY"],
    followUps: ["What if the same user has rows in two regional orders tables?"],
    relatedConcepts: ["outer joins", "aggregation"],
    companiesUse: ["meta", "amazon", "google"],
    timeBenchmarkSeconds: 90,
  },
  {
    id: "sql_easy_003",
    category: "SQL",
    subcategory: "Filtering",
    difficulty: "easy",
    prompt: "From a `transactions` table, return all transactions in the last 30 days where amount > 1000.",
    contextSetup: "transactions(txn_id, user_id, amount, txn_at TIMESTAMP)",
    starterCode: "-- Last 30 days, amount > 1000\nSELECT \n",
    sampleData: "20 transactions spanning 60 days",
    rubric: {
      correctApproach: "WHERE txn_at >= CURRENT_DATE - INTERVAL '30 days' AND amount > 1000",
      commonMistakes: ["hardcoding a date", "off-by-one on date math", "comparing TIMESTAMP to DATE without cast"],
      bonusPoints: ["uses parameterised date", "mentions index on txn_at"],
      traps: ["timezone matters for 'last 30 days' — spec doesn't pin a TZ"],
    },
    expectedKeywords: ["WHERE", "INTERVAL", "CURRENT_DATE"],
    followUps: ["What if the table has a billion rows?"],
    relatedConcepts: ["date math", "indexing"],
    companiesUse: ["stripe", "amazon"],
    timeBenchmarkSeconds: 60,
  },
  {
    id: "sql_easy_004",
    category: "SQL",
    subcategory: "DISTINCT",
    difficulty: "easy",
    prompt: "From a `page_views` table, return the count of unique users who viewed page '/pricing' yesterday.",
    contextSetup: "page_views(view_id, user_id, page_path, viewed_at TIMESTAMP)",
    starterCode: "-- Unique users on /pricing yesterday\nSELECT \n",
    sampleData: "100 page_view rows; 30 on /pricing yesterday across 18 unique users",
    rubric: {
      correctApproach: "COUNT(DISTINCT user_id) WHERE page_path = '/pricing' AND viewed_at::date = CURRENT_DATE - 1",
      commonMistakes: ["COUNT(*) counts views not users", "BETWEEN today and tomorrow excludes yesterday"],
      bonusPoints: ["uses APPROX_COUNT_DISTINCT for scale", "mentions composite index on (page_path, viewed_at)"],
      traps: ["null user_id (anonymous views) — should those count?"],
    },
    expectedKeywords: ["COUNT", "DISTINCT", "WHERE"],
    followUps: ["At 1B rows daily, how would you make this faster?"],
    relatedConcepts: ["distinct counts", "approximation"],
    companiesUse: ["meta", "google", "snowflake"],
    timeBenchmarkSeconds: 75,
  },
  {
    id: "sql_easy_005",
    category: "SQL",
    subcategory: "Aggregation",
    difficulty: "easy",
    prompt: "From `employees(emp_id, dept, salary)`, return the average salary per department, sorted by average descending.",
    contextSetup: "employees(emp_id, dept, salary)",
    starterCode: "-- Avg salary per department, descending\nSELECT \n",
    sampleData: "50 employees across 6 departments",
    rubric: {
      correctApproach: "SELECT dept, AVG(salary) FROM employees GROUP BY dept ORDER BY AVG(salary) DESC",
      commonMistakes: ["forgetting GROUP BY", "ordering by salary not AVG(salary)"],
      bonusPoints: ["rounds to 2 decimals", "labels the column with AS"],
      traps: ["zero employees in a dept → row missing entirely (acceptable, but worth noting)"],
    },
    expectedKeywords: ["AVG", "GROUP BY", "ORDER BY", "DESC"],
    followUps: ["How would you also include median?"],
    relatedConcepts: ["aggregation", "sorting"],
    companiesUse: ["microsoft", "salesforce"],
    timeBenchmarkSeconds: 60,
  },
];
