// SQL — medium bank. Phase 1 seed (5 questions). Expand to 30 in a
// follow-up commit.

import type { InterviewQuestion } from "../types";

export const SQL_MEDIUM: InterviewQuestion[] = [
  {
    id: "sql_med_001",
    category: "SQL",
    subcategory: "Window Functions",
    difficulty: "medium",
    prompt: "From `orders(order_id, customer_id, amount, order_date)`, return each customer's TOP 3 orders by amount. Show customer_id, order_id, amount, and a rank column. Handle ties by amount: tied amounts get the same rank.",
    contextSetup: "orders(order_id, customer_id, amount, order_date)",
    starterCode: "-- Top 3 orders per customer with rank, ties share a rank\nSELECT \n",
    sampleData: "200 orders across 50 customers, including ties",
    rubric: {
      correctApproach: "RANK() OVER (PARTITION BY customer_id ORDER BY amount DESC) — then filter rank ≤ 3 in outer query",
      commonMistakes: ["ROW_NUMBER instead of RANK breaks the ties rule", "DENSE_RANK might be acceptable but spec says 'tied amounts get the same rank' which RANK matches", "WHERE rank ≤ 3 in same query — must be outer query / CTE"],
      bonusPoints: ["uses CTE for readability", "discusses RANK vs DENSE_RANK trade-off", "mentions index on (customer_id, amount)"],
      traps: ["the 'ties share rank' constraint forces RANK, not ROW_NUMBER", "filter on window function must be outer query"],
    },
    expectedKeywords: ["RANK", "PARTITION BY", "ORDER BY", "CTE"],
    followUps: ["Now exclude customers with fewer than 3 orders", "What if amounts can be NULL?"],
    relatedConcepts: ["window functions", "ranking"],
    companiesUse: ["snowflake", "google", "amazon"],
    timeBenchmarkSeconds: 180,
  },
  {
    id: "sql_med_002",
    category: "SQL",
    subcategory: "CTE + Aggregation",
    difficulty: "medium",
    prompt: "Write a query that returns the running 7-day moving average of daily revenue. Output: date, daily_revenue, moving_avg_7d.",
    contextSetup: "transactions(txn_id, amount, txn_at TIMESTAMP)",
    starterCode: "-- 7-day moving average of daily revenue\nWITH daily AS (\n  -- aggregate to daily first\n)\nSELECT \n",
    sampleData: "60 days of transactions, ~1500 rows",
    rubric: {
      correctApproach: "CTE for daily totals, then AVG() OVER (ORDER BY date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)",
      commonMistakes: ["forgetting the ROWS BETWEEN clause (default RANGE behaviour is wrong here)", "computing avg over all dates instead of windowed"],
      bonusPoints: ["uses ROWS BETWEEN explicitly", "handles missing dates (gaps with no transactions)"],
      traps: ["RANGE vs ROWS — RANGE with date can include same-date rows in unexpected ways", "missing dates produce NULL averages or skip — depends on requirement"],
    },
    expectedKeywords: ["WITH", "AVG", "OVER", "ROWS BETWEEN"],
    followUps: ["What if there are dates with zero transactions — how do you fill those in?"],
    relatedConcepts: ["window frames", "time series"],
    companiesUse: ["stripe", "snowflake", "databricks"],
    timeBenchmarkSeconds: 240,
  },
  {
    id: "sql_med_003",
    category: "SQL",
    subcategory: "Self Join",
    difficulty: "medium",
    prompt: "From `employees(emp_id, name, manager_id)`, return every employee with their manager's name. Include employees with no manager (CEO).",
    contextSetup: "employees(emp_id, name, manager_id) — manager_id is FK to emp_id",
    starterCode: "-- Each employee + their manager's name (CEO included)\nSELECT \n",
    sampleData: "30 employees, 1 CEO with NULL manager_id",
    rubric: {
      correctApproach: "LEFT JOIN employees e1 to employees e2 ON e1.manager_id = e2.emp_id",
      commonMistakes: ["INNER JOIN drops the CEO", "joining on emp_id instead of manager_id", "missing aliases creates ambiguous columns"],
      bonusPoints: ["uses COALESCE for the NULL manager case", "uses clear aliases (employee/manager)"],
      traps: ["self-join needs aliases — easy to forget", "NULL manager_id is the right model for top of hierarchy"],
    },
    expectedKeywords: ["LEFT JOIN", "AS", "manager_id"],
    followUps: ["Now find every employee in the CEO's full org chain."],
    relatedConcepts: ["self join", "hierarchy"],
    companiesUse: ["microsoft", "salesforce", "snowflake"],
    timeBenchmarkSeconds: 150,
  },
  {
    id: "sql_med_004",
    category: "SQL",
    subcategory: "Subquery / EXISTS",
    difficulty: "medium",
    prompt: "Return all customers who placed at least one order over $1000 AND at least one order under $50 — both in 2024.",
    contextSetup: "orders(order_id, customer_id, amount, order_date)",
    starterCode: "-- Customers with both a >$1000 and a <$50 order in 2024\nSELECT \n",
    sampleData: "500 orders across 100 customers in 2024",
    rubric: {
      correctApproach: "Two EXISTS subqueries (or HAVING with conditional COUNT) joined by AND",
      commonMistakes: ["IN subquery returns wrong shape", "CASE WHEN inside SUM is fine but easy to get the conditions wrong", "forgetting the year filter"],
      bonusPoints: ["uses HAVING with COUNT(CASE WHEN ...)", "mentions the year filter explicitly"],
      traps: ["the AND-conjunction across two qualitatively-different conditions is the test"],
    },
    expectedKeywords: ["EXISTS", "WHERE", "HAVING", "AND"],
    followUps: ["Now also exclude customers who only placed those two orders all year."],
    relatedConcepts: ["existence quantification", "conditional aggregation"],
    companiesUse: ["amazon", "stripe"],
    timeBenchmarkSeconds: 210,
  },
  {
    id: "sql_med_005",
    category: "SQL",
    subcategory: "Date Math",
    difficulty: "medium",
    prompt: "Return the user retention curve: for users who signed up in Jan 2024, what % were still active (placed an order) in each subsequent month?",
    contextSetup: "users(user_id, signup_at)\norders(order_id, user_id, order_at)",
    starterCode: "-- Retention curve for Jan 2024 cohort\nWITH cohort AS (\n  SELECT user_id FROM users WHERE signup_at >= '2024-01-01' AND signup_at < '2024-02-01'\n)\nSELECT \n",
    sampleData: "1000 users in Jan 2024 cohort, 5000 orders across 2024",
    rubric: {
      correctApproach: "Cohort CTE → cross join with months → LEFT JOIN orders → COUNT DISTINCT active users / cohort size",
      commonMistakes: ["counting orders not unique users", "not including months with zero retention (drops from output)", "off-by-one on month boundaries"],
      bonusPoints: ["generates month series explicitly (handles months with zero activity)", "uses DATE_TRUNC for grouping"],
      traps: ["months with zero activity should still appear at 0%", "COUNT(DISTINCT) is the right aggregation"],
    },
    expectedKeywords: ["WITH", "DATE_TRUNC", "LEFT JOIN", "COUNT", "DISTINCT"],
    followUps: ["How would this change for a different cohort (Feb)? Make it parameterised."],
    relatedConcepts: ["cohort analysis", "retention", "date math"],
    companiesUse: ["meta", "stripe", "snowflake"],
    timeBenchmarkSeconds: 360,
  },
];
